apiVersion: v1
kind: Pod
metadata:
  name: go-demo-2
  labels:
    type: stack
spec:
  containers:
  - name: db
    image: mongo:latest
  - name: api
    image: vfarcic/go-demo-2
    env:
    - name: DB
      value: localhost
